palette = "noctalia"
# ~/.config/starship.toml
command_timeout = 1000
scan_timeout = 30

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[󰜴](bold #ff5555)"
success_symbol = "[󰜴](bold #50fa7b)"
vimcmd_symbol = "[󰜱](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"
read_only = " "

[git_branch]
style = "bold #ff79c6"
symbol = ' '

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"
ssh_symbol = " "

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[python]
symbol = ' '

[package]
symbol = "󰏗 "
disabled = true

[battery]
disabled = true

[sudo]
style = 'bold green'
symbol = ' '
disabled = false

[os.symbols]
Arch = " "

[php]
symbol = '󰌟 '

[lua]
symbol = ' '



























































































































































































































































































































































# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (wallpaper-based)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#ffb4a9"
red       = "#ffb4ab"
green     = "#e7bdb6"
yellow    = "#dec38c"
cyan      = "#e7bdb6"
magenta   = "#ffb4a9"
white     = "#ede0de"
black     = "#181211"

# Extended palette (Catppuccin-compatible names)
rosewater = "#dec38c"
flamingo  = "#dec38c"
pink      = "#ffb4a9"
mauve     = "#9c4237"
maroon    = "#ffb4ab"
peach     = "#dec38c"
teal      = "#e7bdb6"
sky       = "#e7bdb6"
sapphire  = "#e7bdb6"
lavender  = "#9c4237"

# Text shades
text      = "#ede0de"
subtext1  = "#d8c2be"
subtext0  = "#a08c89"

# Surface shades
overlay2  = "#a08c89"
overlay1  = "#d8c2be"
overlay0  = "#534341"
surface2  = "#534341"
surface1  = "#181211"
surface0  = "#181211"
base      = "#181211"
mantle    = "#181211"
crust     = "#3e2e04"
# <<< NOCTALIA STARSHIP PALETTE <<<
