# ~/.config/starship.toml

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[](bold #ff5555)"
success_symbol = "[](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"
symbol = ' '

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[python]
symbol = ' '

[battery]
disabled = true

[sudo]
style = 'bold green'
symbol = '💻'
disabled = false



# [git_branch]
# symbol = ''
# truncation_length = 10
# truncation_symbol = ''
# ignore_branches = ['master', 'main']
