[preferred]
default=kde
org.freedesktop.impl.portal.FileChooser=kde
org.freedesktop.impl.portal.OpenURI=kde
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome
org.freedesktop.impl.portal.Secret=gnome
